### PR TITLE
use g++4.8 to recompile arm64 linux library

### PR DESCRIPTION
**Pull request by cuitianxiang001**
fix "snowboy library built with different ABI for different platform #410"

### CODE REVIEW

**Comment by chenguoguo** [comment]
I'll let @goldegard try it and see if it works.

**Comment by goldegard** [comment]
The issue is solved, although it would be wonderful to have a new ABI version of the lib freeing developers from using wrappers.

**Comment by chenguoguo** [comment]
We'll add the API in the future release.

**Comment by KillingJacky** [comment]
Why not recompile for Raspberry Pi platform as well?

**Pull request merged**
