### PR TITLE
added a new demo program

### PR DESCRIPTION
**Pull request by jopedroliveira**
Added a new demo program for C++ language which allows users to read audio from a file or from the microphone. Specially useful for test purpose

### CODE REVIEW

**Comment by chenguoguo** [comment]
Thanks a lot! Could you format the code a little bit according to https://google.github.io/styleguide/cppguide.html?

High level rules:
1. Don't exceed 80 characters per line
2. Use space instead of tab, two spaces for indentation
3. Delete the unused, commented out code

And also others. Once you clean up the code, I can merge it. Thanks a lot!

**Comment by jopedroliveira** [comment]
Hi,
Of course.
I can also edit the makefile or create another onde if you want.
Cheers,
Pedro.

Em 10/07/2017 01:38, "Guoguo Chen" <notifications@github.com> escreveu:

**Comment by chenguoguo** [comment]
Yes, please update the Makefile as well.

**Comment by chenguoguo** [comment]
Closing this one as it has been merged and renamed to demo2.cc. Thanks a lot for the PR! https://github.com/Kitt-AI/snowboy/commits/b67dc73fe8a53f04edf353cbae8fffdc304739e1/examples/C%2B%2B/demo2.cpp

**Pull request closed without merging**
