### PR TITLE
Builds Android wrapper with make

### PR DESCRIPTION
**Pull request by BillWSY**

### CODE REVIEW

**Comment by chenguoguo** [comment]
Thanks! I'll take a look in the next two days.

**Comment by chenguoguo** [comment]
Generally looks good. I'm going to merge this and add some fixes.

**Comment by chenguoguo** [comment]
@BillWSY I made some small changes so that it can run on Mac OS as well. It will be great if you can check out master and see if it works for you.

**Comment by BillWSY** [comment]
I can confirm that it still works on Linux (Ubuntu 16.04.1 LTS). Thanks.

**Comment by chenguoguo** [comment]
Awesome, thanks!

**Pull request merged**
