### PR TITLE
Updated for python3

### PR DESCRIPTION
**Pull request by Shreyash23**
Updated python-config to python3-config

Should there be a better way to do this?

### CODE REVIEW

**Comment by chenguoguo** [comment]
Thanks for the PR! I'm a little bit reluctant merging it now as it will pull the support for Python2. In some sense Python2 and Python3 are two different languages... Perhaps at some point we should have one directory for Python2 and one for Python3

**Comment by Shreyash23** [comment]
Thanks for responding!

Maybe doing the Python3 should be a priority, considering Python3 is as much of a language as Python2 is, and  snowboy works absolutely fine with Python3 ( I'm using it in my project. )

**Comment by chenguoguo** [comment]
I added an additional directory for Python3, and used python3-config there. Thanks a lot! I'm closing this.

**Comment by Shreyash23** [comment]
Thanks for the update! Was much needed :)

**Pull request closed without merging**
