### PR TITLE
Build node 8.x binaries [republish binary]

### PR DESCRIPTION
**Pull request by evancohen**
Small patch to support node v8.x  
Addresses #212

### CODE REVIEW

**Comment by chenguoguo** [comment]
LGTM. Thanks!

**Comment by henrikra** [comment]
Looks like latest release v1.2.0 is done 3/25/2017? So I guess for example this PR not published yet? What I am missing :D?

**Comment by chenguoguo** [comment]
@evancohen  Do we also have to update the dependencies? I'm seeing errors from travis CI:

https://travis-ci.org/Kitt-AI/snowboy/jobs/320011432

**Comment by evancohen** [comment]
Hmm, we may - but from that error it seems like it's having trouble finding the `nan` package (even though it's a dev dependency).

I think this can be fixed by modifying the Travis config to install `nan` globally. I'll look at this tonight and send a PR with a fix.

**Pull request merged**
